### ISSUE TITLE
For grouped options, add group title to search index

### ISSUE THREAD

**Issue by feldpost** [culturecode/uber_select#17]
When specifying a grouped options as such:

```
Colors
 - Red
 - Green
 - Yellow
```

I should be able to search for the group titles (`Colors`) and results should include all child options along with the group title. 

Currently a search for `colors` will yield no results.

**Comment by feldpost** [comment]
Additional, when the option is selected we should display it with the group name visible: `[Colors] Red`

**Comment by njakobsen** [comment]
Closed by https://github.com/culturecode/uber_select/commit/2efef4fc33f73cf83cb2c58cbfc7c8d74f725703.

To achieve this effect:
- pass `matchGroupNames: true` to when creating an `UberSelect` or `UberSearch`.
- include `data-selected-text` on an UberSelect `<option>` element or set the `selectedText` property on data passed to `UberSearch`.
